version: '3.8'

services:
  # MongoDB 서비스 정의 (완전히 인증 없음)
  mongodb:
    image: mongo:latest
    container_name: file-tagger-db
    # MongoDB 완전히 인증 없이 실행
    command: mongod --noauth --bind_ip_all --port 27017
    ports:
      # 호스트의 27018 포트와 컨테이너의 27017 포트를 연결합니다.
      # PyQt 앱이 localhost:27018로 접속할 수 있게 됩니다.
      - "27018:27017"
    volumes:
      # 데이터베이스 데이터를 호스트 머신에 영구적으로 저장하기 위한 볼륨 설정
      # 'mongodb_data'라는 이름의 Docker 볼륨을 생성하여 사용합니다.
      - mongodb_data:/data/db
    networks:
      - app-network

# 서비스들이 사용할 네트워크 정의
networks:
  app-network:
    driver: bridge

# 데이터 영속성을 위한 명명된 볼륨 정의
volumes:
  mongodb_data:
    driver: local
