version: '3.8'

services:
  # MongoDB 서비스 정의
  mongodb:
    image: mongo:latest
    container_name: file-tagger-db
    # MongoDB 인증을 위한 환경 변수 설정
    # 중요: 실제 프로덕션 환경에서는 이 값을 직접 하드코딩하지 말고,
    # .env 파일을 사용하거나 다른 보안 방식을 통해 주입해야 합니다.
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      # 호스트의 27018 포트와 컨테이너의 27017 포트를 연결합니다.
      # PyQt 앱이 localhost:27018로 접속할 수 있게 됩니다.
      - "27018:27017"
    volumes:
      # 데이터베이스 데이터를 호스트 머신에 영구적으로 저장하기 위한 볼륨 설정
      # 'mongodb_data'라는 이름의 Docker 볼륨을 생성하여 사용합니다.
      - mongodb_data:/data/db
    networks:
      - app-network

# 서비스들이 사용할 네트워크 정의
networks:
  app-network:
    driver: bridge

# 데이터 영속성을 위한 명명된 볼륨 정의
volumes:
  mongodb_data:
    driver: local
